# Generated by Django 4.1 on 2022-09-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_document_datetimeofupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documentos'},
        ),
    ]
