# Generated by Django 4.1.1 on 2022-09-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_responsaveis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsaveis',
            options={'verbose_name': 'Resonsavel', 'verbose_name_plural': 'Responsaveis'},
        ),
        migrations.AddField(
            model_name='conta',
            name='valor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
