# Generated by Django 4.1 on 2022-09-02 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_document_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_origem', models.CharField(max_length=200)),
                ('agencia_origem', models.CharField(max_length=200)),
                ('conta_origem', models.CharField(max_length=200)),
                ('banco_destino', models.CharField(max_length=200)),
                ('agencia_destino', models.CharField(max_length=200)),
                ('conta_destino', models.CharField(max_length=200)),
                ('valor_transacao', models.IntegerField()),
                ('data_hora', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.document')),
            ],
            options={
                'verbose_name': 'Transacao',
                'verbose_name_plural': 'Transacoes',
            },
        ),
    ]
