# Generated by Django 4.1 on 2022-09-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='valor_transacao',
            field=models.FloatField(),
        ),
    ]
